//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoringProg
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_work
    {
        public int id_userW { get; set; }
        public string userW_name { get; set; }
        public string userW_surname { get; set; }
        public string userW_login { get; set; }
        public string userW_password { get; set; }
        public Nullable<int> userW_prava { get; set; }
    }
}
